IdentityApp/Models/AppRole.cs
using Microsoft.AspNetCore.Identity;

namespace IdentityApp.Models 
{
    public class AppRole : IdentityRole
    {

    }
}

IdentityApp/Models/AppUser.cs
using Microsoft.AspNetCore.Identity;

namespace IdentityApp.Models 
{
    public class AppUser : IdentityUser 
    {
        public string? FullName { get; set; } 
    }
}

IdentityApp/Models/DataContext.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace IdentityApp.Models;

public class DataContext : IdentityDbContext<AppUser , AppRole , string> 
{
    public DataContext(DbContextOptions<DataContext> options) : base(options)
    {
        
    }
}   

IdentityApp/Models/ErrorViewModel.cs
namespace IdentityApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

IdentityApp/Models/SeedData.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace IdentityApp.Models;

public static class SeedData
{
    public const string  adminUser = "Admin";
    public const string adminPassword = "Admin_123";

    public static async void IdentityTestUser (IApplicationBuilder app) 
    {
        var context = app.ApplicationServices.CreateScope().ServiceProvider.GetRequiredService<DataContext>();

        if(context.Database.GetAppliedMigrations().Any())
        {
            context.Database.Migrate();
        }

        var userManager = app.ApplicationServices.CreateScope().ServiceProvider.GetRequiredService<UserManager<AppUser>>();

        var user = await userManager.FindByNameAsync(adminUser);

        if(user == null)
        {
            user = new AppUser 
            {
                FullName = "Batuhan Toy" ,
                UserName = adminUser ,
                Email = "admin@batutoy.com" ,
                PhoneNumber = "121212"
            };

            await userManager.CreateAsync(user , adminPassword);
        }
    }
}

IdentityApp/ViewModels/CreateViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace  IdentityApp.ViewModels;

public class CreateViewModel 
{
    [Required]
    public string FullName { get; set; } = string.Empty;

    [Required]
    [EmailAddress]
    public string Email { get; set; } = string.Empty;

    [Required]
    [DataType(DataType.Password)]
    public string Password { get; set; } = string.Empty;
    
    [Required]
    [DataType(DataType.Password)]
    [Compare(nameof(Password) , ErrorMessage = "Parolanız eşleşmiyor.")]
    public string ConfirmPassword { get; set; } = string.Empty;
    
}

IdentityApp/ViewModels/EditViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace  IdentityApp.ViewModels;

public class EditViewModel 
{
    public string? Id { get; set; }
    public string? FullName { get; set; } 

    
    [EmailAddress]
    public string? Email { get; set; } 

    [StringLength(8 ,  ErrorMessage = "Şifreniz en az 8 karakter uzunluğunda olmalıdır.")]
    [DataType(DataType.Password)]
    public string? Password { get; set; } 
    

    [DataType(DataType.Password)]
    [Compare("Password" , ErrorMessage = "Parolanız eşleşmiyor.")]
    public string? ConfirmPassword { get; set; } 
    
}

IdentityApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using IdentityApp.Models;

namespace IdentityApp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

IdentityApp/Controllers/RoleController.cs
using IdentityApp.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace IdentityApp.Controllers;

public class RoleController : Controller
{
    private readonly RoleManager<AppRole> _roleManager;
    public RoleController(RoleManager<AppRole> roleManager)
    {
        _roleManager = roleManager;
    }
    public IActionResult Index()
    {
        return View();
    }
    public IActionResult Create()
    {
        return View();
    }   
    [HttpPost]
    public async Task<IActionResult> Create(AppRole model)
    {
        if(ModelState.IsValid)
        {
            // var Role = new AppRole { Id = model.Id , Name = model.Name ,
            // ConcurrencyStamp = model.ConcurrencyStamp  , NormalizedName = model.NormalizedName };

            var result = await _roleManager.CreateAsync(model);

            if(result.Succeeded)
            {
                return RedirectToAction("Index");   
            }

            foreach(var err in result.Errors)
            {
                ModelState.AddModelError("" , err.Description);
            }

        }

        return View(model);
    }
    
}

IdentityApp/Controllers/UserController.cs
using IdentityApp.Models;
using IdentityApp.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace IdentityApp.Controllers;

public class UserController : Controller 
{
    
    private readonly UserManager<AppUser> _userManager ;
    
    public UserController(UserManager<AppUser> userManager)
    {
        _userManager = userManager;
    }
    public IActionResult Index() 
    {
        return View(_userManager.Users);
    }
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(CreateViewModel model)
    {
        if(ModelState.IsValid)
        {
           var user = new AppUser { UserName = model.Email , FullName = model.FullName , Email = model.Email };
        
            var result = await _userManager.CreateAsync(user , model.Password);

            if(result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            foreach(var err in result.Errors)
            {
                ModelState.AddModelError("" , err.Description);
            } 
        }
        return View(model);
    }
    [HttpPost]
    public async Task<IActionResult> Delete(string id)
    {
        var user = await _userManager.FindByIdAsync(id);

        if(user != null)
        {
            await _userManager.DeleteAsync(user);
        }
        return RedirectToAction("Index");
    }
   public async Task<IActionResult> Edit(string Id)
    {
        if(Id == null)
        {
            return RedirectToAction("Index" , "Home");
        }
        
        var user = await _userManager.FindByIdAsync(Id);

        if(user != null)
        {
            return View( new EditViewModel {
                Id = user.Id ,
                FullName = user.FullName ,
                Email = user.Email
            });
        }

        return RedirectToAction("Index");
    }
    [HttpPost]
    public async Task<IActionResult> Edit(string Id , EditViewModel model)
    {
        if(Id != model.Id)
        {
            return RedirectToAction("Index");
        }

        if(ModelState.IsValid)
        {
            var user = await _userManager.FindByIdAsync(model.Id);

            if(user != null)
            {
                user.FullName = model.FullName;
                user.Email = model.Email;
                
                var result = await  _userManager.UpdateAsync(user);

                if(result.Succeeded && !string.IsNullOrEmpty(model.Password))
                {
                    await _userManager.RemovePasswordAsync(user);
                    await _userManager.AddPasswordAsync(user , model.Password);
                }

                if(result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach(IdentityError err in result.Errors)
                {
                    ModelState.AddModelError("", err.Description);
                }
            }
        }
        return View(model);
    }
}

IdentityApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

IdentityApp/Views/Role/Create.cshtml
@model AppRole

<h2>Create Role</h2>
<hr>
<form action="Create" method="POST">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Authorize</button>
</form>

IdentityApp/Views/Role/Index.cshtml
@model List<AppRole>

<a class="btn btn-primary"  asp-action="Create" >Add Role</a>
<hr>

IdentityApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IdentityApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IdentityApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IdentityApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Role" asp-action="Index">Roles</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - IdentityApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

IdentityApp/Views/User/Create.cshtml
@model CreateViewModel

<h2>Create User</h2>
<hr>
<form action="Create" method="POST">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="mb-3">
        <label asp-for="FullName"></label>
        <input asp-for="FullName" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Password"></label>
        <input asp-for="Password" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="ConfirmPassword"></label>
        <input asp-for="ConfirmPassword" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
</form>

IdentityApp/Views/User/Edit.cshtml
@model EditViewModel

<h2>Edit User</h2>
<hr>
<form action="Edit" method="POST">
    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="hidden" name="Id" value="@Model.Id">
    <div class="mb-3">
        <label asp-for="FullName"></label>
        <input asp-for="FullName" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="card">
        <div class="card-header">
            Change Password
        </div>
        <div class="card-body">
            <div class="mb-3">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="ConfirmPassword"></label>
                <input asp-for="ConfirmPassword" class="form-control">
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary mt-3">Add</button>
</form>

IdentityApp/Views/User/Index.cshtml
@model IEnumerable<AppUser>

<a class="btn btn-primary"  asp-action="Create" >Add User</a>
<hr>
<table class="table table-sm table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th style="width: 120px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var user in Model)
        {
            <tr>
                <td>@user.Id</td>
                <td>@user.FullName</td>
                <td>@user.Email</td>
                <td>
                    <a asp-action = "Edit"  asp-route-id="@user.Id"  class="btn btn-primary btn-sm">Edit</a>
                    <form asp-action="Delete" method="POST" onsubmit =" return confirm('Are you sure?')" style = "display: inline-block;"> 
                    <input type="hidden" name="id" value="@user.Id">
                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                    </form> 
                </td>
            </tr>
        }
    </tbody>
</table>   